---
permalink: concept-overview-rest-apis.html
sidebar: sidebar
keywords: REST APIs
summary: "Provides an overview of the supported REST APIs."
---
= Overview
:icons: font
:imagesdir: ../media/

[.lead]
You can use the BlueXP backup and recovery for VMs REST APIs to perform common data protection operations. 

* REST API workflows are documented for the following operations on VMs and datastores using the REST APIs for VMware vSphere:
** Add, modify, and delete storage VMs and clusters
** Create, modify, and delete resource groups
** Backup VMs, scheduled and on-demand
** Restore existing VMs and deleted VMs
** Restore VMDKs
** Attach and detach VMDKs
** Mount and unmount datastores
** Download jobs and generate reports
** Modify built-in schedules

* Operations that are not supported by the REST APIs for VMware vSphere
** Guest file restore
** Installation and configuration of the BlueXP backup and recovery for VMs
** Assign RBAC roles or access to users

* uri parameter
** The uri parameter always returns a "null" value.

* Login timeout
** The default timeout is 120 minutes (2 hours). You can configure a different timeout value in the vCenter settings.

* Token management
+
For security, REST APIs use a mandatory token that is passed with each request and is used in all API calls for client validation. The REST APIs for VMware vSphere use the VMware authentication API to obtain the token. VMware provides the token management.
+
To obtain the token, use /1.1/auth/login REST API and provide the vCenter credentials.

* API version designations
+
Each REST API name includes the BlueXP backup and recovery for VMs version number in which the REST API was first released.
+
REST APIs in future releases will usually be backward compatible and will be modified to accommodate new features as needed.