---
permalink: concept-bluexp-backup-and-recovery-for-virtual-machines-on-amazon-fsx.html
sidebar: sidebar
keywords: bluexp, backup, recovery, virtual machines, amazon fsx
summary: "BlueXP backup and recovery for VMs is a standalone virtual appliance (Open Virtual Appliance format) that provides data protection services for VMs and datastores on VMware Cloud on AWS and Amazon FSx for NetApp ONTAP. You can use BlueXP backup and recovery for VMs to back up datastores and restore virtual machines to their original location."
---
= BlueXP backup and recovery for virtual machines on Amazon FSx
:icons: font
:imagesdir: ../media/

[.lead]
BlueXP backup and recovery for VMs is a standalone virtual appliance (Open Virtual Appliance format) that provides data protection services for VMs and datastores on VMware Cloud on AWS and Amazon FSx for NetApp ONTAP. You can use BlueXP backup and recovery for VMs to back up datastores and restore virtual machines to their original location.

* You can backup only NFS type datastores on Amazon FSx.
* You should be running ONTAP 9.10 or later to backup NFS datastores. 
* VMware Cloud comes with a pre-defined “CloudAdmin” role. The CloudAdmin role has the necessary privileges to create and manage SDDC workloads and related objects such as storage policies, content libraries, vSphere tags, and resource pools.
* You can restore VMs and VMDK to their current location (in-place restore).

This document describes how to deploy and use BlueXP backup and recovery for VMs.


