settings:
  name: "BlueXP backup and recovery for VMs"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
  # harmony_enabled: true

sidebar: 
  entries:
  - title: BlueXP backup and recovery for VMs documentation
    url: /index.html
  - title: Release notes
    url: /release-notes.html
    entries:
      - title: What’s new in this release
        url: /whats-new.html
  - title: BlueXP backup and recovery for virtual machines on Amazon FSx
    url: /concept-bluexp-backup-and-recovery-for-virtual-machines-on-amazon-fsx.html
    entries:
      - title: Unsupported workflows
        url: /concept-unsupported-workflows.html
  - title: Deploy BlueXP backup and recovery for VMs
    url: /concept-deploy-bluexp-backup-and-recovery-for-vms.html
    entries:
      - title: Requirements and considerations
        url: /reference-requirements-and-considerations.html
      - title: Download the Open Virtual Appliance (OVA)
        url: /task-download-the-open-virtual-appliance.html
      - title: Deploy BlueXP backup and recovery for VMs
        url: /task-deploy-bluexp-backup-and-recovery-for-vms.html
  - title: Back up a NFS datastore to Amazon FSx        
    entries:
      - title: Add storage
        url: /task-add-storage.html
      - title: Create backup policies for VMs and datastores
        url: /task-create-backup-policies-for-vms-and-datastores.html
      - title: Create resource groups
        url: /task-create-resource-groups.html
      - title: Back up resource groups on demand
        url: /task-back-up-resource-groups-on-demand.html 
  - title: Restore Virtual Machines from Amazon FSx
    url: /task-restore-virtual-machines-from-amazon-fsx.html
  - title: Legal notices
    url: /legal-notices.html
