settings:
  name: "BlueXP backup and recovery for VMs"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar: 
  entries:
  - title: BlueXP backup and recovery for VMs docs
    url: /index.html
  - title: Release notes
    url: /whats-new.html
  - title: Get started
    entries: 
      - title: Learn about BlueXP backup and recovery for VMs
        url: /concept-bluexp-backup-and-recovery-for-virtual-machines-on-amazon-fsx.html
      - title: Unsupported workflows
        url: /concept-unsupported-workflows.html
  - title: Deploy BlueXP backup and recovery for VMs
    entries:
      - title: Requirements and considerations
        url: /reference-requirements-and-considerations.html
      - title: Download the OVA
        url: /task-download-the-open-virtual-appliance.html
      - title: Deploy BlueXP backup and recovery for VMs
        url: /task-deploy-bluexp-backup-and-recovery-for-vms.html
  - title: Backup NFS datastore to Amazon FSx        
    entries:
      - title: Add storage
        url: /task-add-storage.html
      - title: Create backup policies
        url: /task-create-backup-policies-for-vms-and-datastores.html
      - title: Create resource groups
        url: /task-create-resource-groups.html
      - title: Back up resource groups on demand
        url: /task-back-up-resource-groups-on-demand.html 
  - title: Restore Virtual Machines from Amazon FSx
    url: /task-restore-virtual-machines-from-amazon-fsx.html
  - title: Knowledge and support
    entries:
      - title: Register for support
        url: /task-support-registration.html
      - title: Get help
        url: /task-get-help.html
  - title: Legal notices
    url: /legal-notices.html
