---
permalink: task-access-rest-apis.html
sidebar: sidebar
keywords: access REST APIs, REST APIs
summary: 'Perform these steps to access the REST APIs.'
---
= Access REST APIs using the Swagger API web page
:icons: font
:imagesdir: ./media/

[.lead]
REST APIs are exposed through the Swagger web page. You can access the Swagger web page to display the BlueXP backup and recovery for VMs REST APIs. 

.Before you begin
For BlueXP backup and recovery for VMs REST APIs, you must know either the IP address or the host name of the BlueXP backup and recovery for VMs appliance.

NOTE: The plug-in only supports REST APIs for the purpose of integrating with third party applications and does not support PowerShell cmdlets or a CLI.

.Steps
. From a browser, enter the URL to access the plug-in Swagger web page:
+
https://<OVA_IP>/api/swagger-ui/index.html[]
+
NOTE: Do not use the following characters in the REST API URL: +, . , %, and &.
+
*Example*
+
Access the SnapCenter VMware plug-in REST APIs:
+
https://<OVA_IP>/api/swagger-ui/index.html
+
Log in use the vCenter authentication mechanism to generate the token.

. Click an API resource type to display the APIs in that resource type.