---
permalink: task-unmount-datastores.html
sidebar: sidebar
keywords: mount, datastores
summary: 'Unmounting a datastore removes host access to storage.'
---
= Unmount datastores
:experimental:
:icons: font
:imagesdir: ./media/

[.lead]
You can unmount a backup when you no longer need to access the files in the datastore.

.Steps

. In the VMware vSphere client toolbar, click *Storage*, and then select the storage system from the drop-down list.
. In the left Navigator pane, click *Backups*.
. Select a mounted datastore and click *Unmount*.

NOTE: Make sure that you select the correct datastore to unmount. Otherwise, you might cause an impact on production work.

. In the *Unmount Backup* dialog box, select a datastore, select the *Unmount the datastore* checkbox, and click *Unmount*.
. Optional: To verify that the datastore is unmounted, in the VMware vSphere client toolbar, click *BlueXP backup and recovery for VMs*.
+
The datastore you unmounted is displayed in the *Recent Job Activities* tile of the dashboard.