---
permalink: task-detach-virtual-disks.html
sidebar: sidebar
keywords: mount, datastores
summary: 'Attach one ore more VMDKs to the VM.'
---
= Detach a virtual disk
:experimental:
:icons: font
:imagesdir: ./media/

[.lead]
After you have attached a virtual disk to restore individual files, you can detach the virtual disk from the parent VM.

.Steps


. In the left Navigator pane, right-click a *Virtual Machine*, then select *BlueXP backup and recovery for VMs* in the drop-down list, and then select *Detach Virtual Disk(s)*.
. In the *Detach Virtual Disk* dialog box, select one or more disks you want to detach, then select the *Detach the selected disk(s)* checkbox, and click*Detach*.
. Optional: Monitor the operation progress in the *Recent Tasks* section.
+
Refresh the screen to display updated information.

. Verify that the virtual disk is attached by performing the following:

.. Click *Menu* in the toolbar, and then select *VMs and Templates* from the drop-down list.

.. In the left Navigator pane, right-click a VM, then select *Edit settings* in the drop-down list.

.. In the *Edit Settings* window, expand the list for each hard disk to see the list of disk files.
+
The Edit Settings page lists the disks on the VM. You can expand the details for each hard disk to see the list of attached virtual disks.

*Result*
You can access the attached disks from the host operating system and then retrieve the needed information from the disks.
