---
permalink: task-download-the-open-virtual-appliance.html
sidebar: sidebar
keywords: download, open virtual appliance
summary: 'Download the Open Virtual Appliance (OVA) in VMware vCenter 8.0 and above to deploy BlueXP backup and recovery for VMs.'
---
= Download the Open Virtual Appliance
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
Download the Open Virtual Appliance (OVA) in VMware vCenter 8.0 and above to deploy BlueXP backup and recovery for VMs.

.Before you begin
If the OVA signed by the Entrust certificate is not trusted, ensure to install and add the intermediate certificates to the vCenter. 

.Steps
. To download BlueXP backup and recovery for VMs OVA:
.. Log in to the https://mysupport.netapp.com/products/index.html[NetApp Support Site^]
.. From the list of products, select *BlueXP backup and recovery for VMs*, then click the *Download Latest Release* button.
.. Download the BlueXP backup and recovery for VMs `.tar` file to any location.

. Extract the contents of the tar file. The tar file contains the OVA and certs folder. The certs folder contains Intermediate certificates.
. In vSphere client, navigate to *Administration > Certificates > Certificate Management*.
. Next to *Trusted Root certificates*, click *Add*.
+
NOTE: By default, the root certificate is installed.

.. Go to the certs folder.
.. Select the Intermediate certificates.
.. Install each certificate one at a time.

. The certificates are added to a panel under Trusted Root Certificates.

+
Once the certificates are installed, OVA can be verified and deployed.

[NOTE]
====
If the downloaded OVA is not tampered, then the Publisher column displays Trusted certificate.
====