---
permalink: task-attach-vmdks-vm.html
sidebar: sidebar
keywords: mount, datastores
summary: 'Attach one ore more VMDKs to the VM.'
---
= Attach VMDKs to a VM
:experimental:
:icons: font
:imagesdir: ./media/

[.lead]
You can attach one or more VMDKs from a backup to the parent VM, or to an alternate VM on the same ESXi host, or to an alternate VM on an alternate ESXi host managed by the same vCenter or a different vCenter in linked mode. VMs in traditional datastores and in vVol datastores are supported.

This makes it easier to restore one or more individual files from a drive instead of restoring the entire drive. You can detach the VMDK after you have restored or accessed the files you need.

.About this task

You have the following attach options:
* You can attach virtual disks from a primary or a secondary backup.
* You can attach virtual disks to the parent VM (the same VM that the virtual disk was originally associated with) or to an alternate VM on the same ESXi host.

The following limitations apply to attaching virtual disks:

* Attach and detach operations are not supported for Virtual Machine Templates.

.Steps
. In the left Navigator pane, right-click a *Virtual Machine*, then select *BlueXP backup and recovery for VMs* in the drop-down list, and then select *Attach Virtual Disk(s)*.
. On the Attach Virtual Disk window, in the *Backup section*, select a backup.
+
You can filter the backup list by selecting the filter icon and choosing a date and time range, selecting whether you want backups that contain VMware Snapshot copies, whether you want mounted backups, and the location. Click OK.

. In the *Select Disks* section, select one or more disks you want to attach and the location you want to attach from (primary or secondary).
+
You can change the filter to display primary and secondary locations.

. By default, the selected virtual disks are attached to the parent VM. To attach the selected virtual disks to an alternate VM in the same ESXi host, *click Click here to attach to alternate VM* and specify the alternate VM.

. Click *Attach*.

. Optional: Monitor the operation progress in the *Recent Tasks* section.
+
Refresh the screen to display updated information.

. Verify that the virtual disk is attached by performing the following:

.. Click *Menu* in the toolbar, and then select *VMs and Templates* from the drop-down list.

.. In the left Navigator pane, right-click a VM, then select *Edit settings* in the drop-down list.

.. In the *Edit Settings* window, expand the list for each hard disk to see the list of disk files.
+
The Edit Settings page lists the disks on the VM. You can expand the details for each hard disk to see the list of attached virtual disks.

*Result*
You can access the attached disks from the host operating system and then retrieve the needed information from the disks.

